[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements-simple.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python3 app.py"
