[phases.setup]
nixPkgs = ["python39", "opencv", "ffmpeg"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python3 app.py"
