services:
  - type: web
    name: jarvis-assistant
    runtime: python
    buildCommand: pip install -r requirements_complete.txt
    startCommand: python app_complete.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false  # Set this in Render dashboard